/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as NoRoleRouteImport } from './routes/no-role'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicNotifyPushRouteImport } from './routes/api/public/notify-push'

const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const NoRoleRoute = NoRoleRouteImport.update({
  id: '/no-role',
  path: '/no-role',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyPushRoute = ApiPublicNotifyPushRouteImport.update({
  id: '/api/public/notify-push',
  path: '/api/public/notify-push',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/driver': typeof DriverRoute
  '/login': typeof LoginRoute
  '/no-role': typeof NoRoleRoute
  '/restaurant': typeof RestaurantRoute
  '/api/public/notify-push': typeof ApiPublicNotifyPushRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/driver': typeof DriverRoute
  '/login': typeof LoginRoute
  '/no-role': typeof NoRoleRoute
  '/restaurant': typeof RestaurantRoute
  '/api/public/notify-push': typeof ApiPublicNotifyPushRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/driver': typeof DriverRoute
  '/login': typeof LoginRoute
  '/no-role': typeof NoRoleRoute
  '/restaurant': typeof RestaurantRoute
  '/api/public/notify-push': typeof ApiPublicNotifyPushRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/driver'
    | '/login'
    | '/no-role'
    | '/restaurant'
    | '/api/public/notify-push'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/driver'
    | '/login'
    | '/no-role'
    | '/restaurant'
    | '/api/public/notify-push'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/driver'
    | '/login'
    | '/no-role'
    | '/restaurant'
    | '/api/public/notify-push'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DriverRoute: typeof DriverRoute
  LoginRoute: typeof LoginRoute
  NoRoleRoute: typeof NoRoleRoute
  RestaurantRoute: typeof RestaurantRoute
  ApiPublicNotifyPushRoute: typeof ApiPublicNotifyPushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-role': {
      id: '/no-role'
      path: '/no-role'
      fullPath: '/no-role'
      preLoaderRoute: typeof NoRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-push': {
      id: '/api/public/notify-push'
      path: '/api/public/notify-push'
      fullPath: '/api/public/notify-push'
      preLoaderRoute: typeof ApiPublicNotifyPushRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DriverRoute: DriverRoute,
  LoginRoute: LoginRoute,
  NoRoleRoute: NoRoleRoute,
  RestaurantRoute: RestaurantRoute,
  ApiPublicNotifyPushRoute: ApiPublicNotifyPushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
